---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_os_family != 'FreeBSD'

- name: Restart shard-manifest
  ansible.builtin.service:
    name: "{{ 'shard-manifest' if ansible_os_family != 'FreeBSD' else 'shard_manifest' }}"
    state: restarted
