---
- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
  when: ansible_os_family != 'FreeBSD'

- name: Reload pf
  ansible.builtin.command: pfctl -f /etc/pf.conf
  when: ansible_os_family == 'FreeBSD'
  changed_when: true
